[package]
name = "ytermusic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustube = { path = "./rustube", features = [
    "download",
    "std",
    "rustls-tls",
], default-features = false }
tokio = { version = "*", features = ["full"] }
futures-util = "0.3.21"
once_cell = "1.10.0"
ytpapi = { path = "./ytpapi" }
flume = "0.10.12"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
player = { path = "player" }
crossterm = "0.23.2"
tui = "0.17.0"
urlencoding = "2.1.0"

[profile.release]
lto = true
opt-level = 3
debug = false
codegen-units = 1
