[package]
name = "ytermusic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#  --- YT Download ---
rustube = { path = "./rustube", features = [
    "download",
    "std",
    "rustls-tls",
], default-features = false }
ytpapi = { path = "./ytpapi" }

#  --- Threading & Sync ---
tokio = { version = "*", features = ["rt-multi-thread"] }
once_cell = "1.10.0"
flume = "0.10.12"

#  --- Encoding ---
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
bincode = { version = "1.0.8" }
urlencoding = "2.1.0"
varuint = "0.6.0"

#  --- UI ---
crossterm = "0.23.2"
tui = "0.17.0"

#  --- Player ---
player = { path = "player" }


#  --- Media Control --- 
souvlaki = "0.5.1"

[target."cfg(target_os = \"windows\")".dependencies]
winit = "0.26.1"
raw-window-handle = "0.4.3"

[profile.release]
lto = true
opt-level = 3
debug = false
codegen-units = 1
